# Generated by Django 5.2.8 on 2025-11-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADVISOR', 'Advisor'), ('STATE_MINISTER', 'State Minister'), ('STRATEGIC_STAFF', 'Strategic Affairs Staff'), ('EXECUTIVE', 'Strategic Affairs Executive Officer'), ('LEAD_EXECUTIVE_BODY', 'Lead Executive Body'), ('MINISTER_VIEW', 'Minister (Read Only)')], default='ADVISOR', max_length=32),
        ),
    ]
