# Generated by Django 5.2.8 on 2025-11-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADVISOR', 'Advisor'), ('STATE_MINISTER', 'State Minister'), ('STRATEGIC_STAFF', 'Strategic Affairs Staff'), ('EXECUTIVE', 'Strategic Affairs Executive Officer'), ('LEAD_EXECUTIVE_BODY', 'Lead Executive Body'), ('MINISTER_VIEW', 'Minister (Read Only)')], default='ADVISOR', max_length=32),
        ),
    ]
