# Generated by Django 5.2.8 on 2025-11-24 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_indicatorgroup_indicator_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='indicators.indicatorgroup'),
        ),
    ]
