# Generated by Django 5.2.8 on 2025-11-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_alter_indicator_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='group',
        ),
        migrations.AddField(
            model_name='indicator',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='indicators', to='indicators.indicatorgroup'),
        ),
    ]
