# Generated by Django 5.2.8 on 2026-02-12 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_remove_indicator_group_indicator_groups'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicatorgroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='indicatorgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='indicators.indicatorgroup'),
        ),
        migrations.AddField(
            model_name='indicatorgroup',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit of measurement for this group and its indicators', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='indicatorgroup',
            unique_together={('name', 'department', 'parent')},
        ),
    ]
