# Generated by Django 5.2.8 on 2026-02-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_add_missing_columns'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together=set(),
        ),
    ]
