# Generated by Django 5.2.8 on 2026-02-26 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_remove_indicator_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorgroup',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector_indicator_groups', to='indicators.stateministersector'),
        ),
        migrations.AlterField(
            model_name='indicatorgroup',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_groups', to='indicators.department'),
        ),
    ]
