# Generated by Django 5.2.8 on 2026-02-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_add_sector_to_indicator_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicatorgroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='indicator',
            name='is_aggregatable',
            field=models.BooleanField(default=True, help_text="Whether this indicator's value should be included in parent group calculations"),
        ),
        migrations.AddConstraint(
            model_name='indicatorgroup',
            constraint=models.UniqueConstraint(fields=('name', 'department', 'parent'), name='unique_group_department'),
        ),
        migrations.AddConstraint(
            model_name='indicatorgroup',
            constraint=models.UniqueConstraint(fields=('name', 'sector', 'parent'), name='unique_group_sector'),
        ),
        migrations.AddConstraint(
            model_name='indicatorgroup',
            constraint=models.CheckConstraint(condition=models.Q(('department__isnull', False), ('sector__isnull', False), _connector='OR'), name='group_must_have_department_or_sector'),
        ),
    ]
