# Generated by Django 5.2.8 on 2026-02-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_add_is_aggregatable_field'),
    ]

    operations = [
    ]
