# Generated by Django 5.2.8 on 2026-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_update_existing_indicators_aggregatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='applicable_quarters',
            field=models.JSONField(default=list, help_text='List of applicable quarters: [1, 2, 3, 4]. Empty list means all quarters apply'),
        ),
    ]
