# Generated by Django 5.2.8 on 2026-03-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0012_data_migration_quarter_applicability'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='is_incremental',
            field=models.BooleanField(default=False, help_text="Whether this indicator's performance should be calculated incrementally (cumulative)"),
        ),
    ]
