# Generated by Django 5.2.8 on 2026-03-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0013_indicator_is_incremental'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorgroup',
            name='is_label',
            field=models.BooleanField(default=False, help_text='Whether this indicator group is a label'),
        ),
    ]
