# Generated by Django 5.2.8 on 2025-11-13 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annualplan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annual_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annualplan',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_plans', to='indicators.indicator'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='annual_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plans.annualplan'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarterlybreakdown',
            name='final_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_breakdowns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarterlybreakdown',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_breakdown', to='plans.annualplan'),
        ),
        migrations.AddField(
            model_name='quarterlybreakdown',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_breakdowns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarterlybreakdown',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_breakdowns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarterlybreakdown',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_breakdowns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarterlyperformance',
            name='final_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_performances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarterlyperformance',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='plans.annualplan'),
        ),
        migrations.AddField(
            model_name='quarterlyperformance',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_performances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarterlyperformance',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_performances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarterlyperformance',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_performances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plans.quarterlyperformance'),
        ),
        migrations.AlterUniqueTogether(
            name='annualplan',
            unique_together={('year', 'indicator')},
        ),
        migrations.AlterUniqueTogether(
            name='quarterlyperformance',
            unique_together={('plan', 'quarter')},
        ),
    ]
