# Generated by Django 5.2.8 on 2025-11-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_type', models.CharField(choices=[('BREAKDOWN', 'Annual Breakdown'), ('PERFORMANCE_Q1', 'Performance Q1'), ('PERFORMANCE_Q2', 'Performance Q2'), ('PERFORMANCE_Q3', 'Performance Q3'), ('PERFORMANCE_Q4', 'Performance Q4')], max_length=32)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Optional. If empty, applies to all years.', null=True)),
                ('always_open', models.BooleanField(default=False)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['window_type', 'year', 'active'], name='plans_submi_window__74dde6_idx')],
            },
        ),
    ]
