# Generated by Django 5.2.8 on 2025-12-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_advisorcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterlyperformance',
            name='variance_description',
            field=models.TextField(blank=True),
        ),
    ]
