# Generated by Django 5.2.8 on 2025-12-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_quarterlyperformance_variance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterlybreakdown',
            name='sent_to_strategic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarterlyperformance',
            name='sent_to_strategic',
            field=models.BooleanField(default=False),
        ),
    ]
