# Generated by Django 5.2.8 on 2026-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_quarterlybreakdown_sent_to_strategic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarterlybreakdown',
            name='q1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlybreakdown',
            name='q2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlybreakdown',
            name='q3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlybreakdown',
            name='q4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlyperformance',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
