"""
Django settings for moa_agriplan_system project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import environ

env = environ.Env()

# ============================================
# BASE DIRECTORY
# ============================================

BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(str(BASE_DIR / '.env'))

# ============================================
# SECURITY
# ============================================

SECRET_KEY = env('SECRET_KEY', default='change-me')

DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[
    'localhost',
    '127.0.0.1',
    '10.10.20.233',
    '196.188.248.104',
    'pms.moa.gov.et',
    'backend',
    'moa-backend-prod',
])

# ============================================
# APPLICATIONS
# ============================================

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',

    'users',
    'indicators',
    'plans',
]

# ============================================
# MIDDLEWARE
# ============================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'moa_agriplan_system.urls'

# ============================================
# TEMPLATES
# ============================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'moa_agriplan_system.wsgi.application'

# ============================================
# DATABASE
# ============================================

DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': env('DB_NAME', default='planningmanagmentdb'),
        'USER': env('DB_USER', default='postgres'),
        'PASSWORD': env('DB_PASSWORD', default=''),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5432'),
    }
}

# ============================================
# PASSWORD VALIDATION
# ============================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ============================================
# INTERNATIONALIZATION
# ============================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Addis_Ababa'

USE_I18N = True
USE_TZ = True

# ============================================
# STATIC & MEDIA FILES
# ============================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================
# DEFAULT PRIMARY KEY
# ============================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# CUSTOM USER MODEL
# ============================================

AUTH_USER_MODEL = 'users.User'

# ============================================
# DJANGO REST FRAMEWORK
# ============================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# ============================================
# CORS SETTINGS
# ============================================

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    "https://pms.moa.gov.et",
    "http://pms.moa.gov.et",

    "http://196.188.248.104",
    "http://196.188.248.104:8080",

    "http://10.10.20.233:3000",
    "http://10.10.20.233:8080",

    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:5174",
]

# ============================================
# CSRF SETTINGS
# ============================================

CSRF_TRUSTED_ORIGINS = [
    "https://pms.moa.gov.et",
    "http://pms.moa.gov.et",

    "http://196.188.248.104",
    "http://196.188.248.104:8000",

    "http://10.10.20.233",
    "http://10.10.20.233:8000",

    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:5174",
]

# ============================================
# HTTPS / NGINX REVERSE PROXY SETTINGS
# ============================================

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SECURE_SSL_REDIRECT = False

SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# ============================================
# QUARTERLY BREAKDOWN SETTINGS
# ============================================

BREAKDOWN_WINDOW_ALWAYS_OPEN = env.bool(
    'BREAKDOWN_WINDOW_ALWAYS_OPEN',
    default=False
)

BREAKDOWN_WINDOW_START_MONTH = env.int(
    'BREAKDOWN_WINDOW_START_MONTH',
    default=1
)

BREAKDOWN_WINDOW_START_DAY = env.int(
    'BREAKDOWN_WINDOW_START_DAY',
    default=1
)

BREAKDOWN_WINDOW_DURATION_DAYS = env.int(
    'BREAKDOWN_WINDOW_DURATION_DAYS',
    default=15
)